import { spawnSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { createConnection } from "node:net";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { checkPwaSourceContract, formatPwaContractProblems } from "./pwa-contract.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const results = [];
const add = (code, status, summary, remedy) => results.push({ code, status, summary, ...(remedy ? { remedy } : {}) });

const nodeMajor = Number(process.versions.node.split(".")[0]);
add(
  "VIR-ENV-001",
  nodeMajor === 24 ? "pass" : "fail",
  `Node ${process.versions.node}`,
  "Install Node 24.15 or newer, but below 25.",
);

const osRelease = existsSync("/etc/os-release") ? readFileSync("/etc/os-release", "utf8") : "";
const kernelRelease = existsSync("/proc/sys/kernel/osrelease")
  ? readFileSync("/proc/sys/kernel/osrelease", "utf8")
  : "";
const ubuntu2404 = /^ID=ubuntu$/mu.test(osRelease) && /^VERSION_ID="?24\.04"?$/mu.test(osRelease);
const wsl = /microsoft/iu.test(kernelRelease);
const commandIsGnu = executable => {
  const completed = spawnSync(executable, ["--version"], { encoding: "utf8" });
  return completed.status === 0 && /GNU/iu.test(`${completed.stdout ?? ""}\n${completed.stderr ?? ""}`);
};
const supportedHost = process.platform === "linux" && process.arch === "x64" && ubuntu2404 && !wsl;
const verificationTools = commandIsGnu("/usr/bin/time") && commandIsGnu("date");
add(
  "VIR-VERIFY-001",
  supportedHost && verificationTools ? "pass" : supportedHost ? "fail" : "warn",
  supportedHost && verificationTools
    ? "Authoritative verification host: Ubuntu 24.04 x86-64 with GNU time/date"
    : supportedHost
      ? "Ubuntu 24.04 x86-64 is missing GNU time or GNU date"
      : (wsl ? "Windows/WSL2" : process.platform + "/" + process.arch) +
        " is outside the supported local verification host",
  supportedHost
    ? "Install GNU time and coreutils before running corepack npm run verify."
    : "Use Ubuntu 24.04 x86-64 for release evidence; this host remains untested until an automated support lane exists.",
);

let metadata;
try {
  metadata = JSON.parse(readFileSync(resolve(root, ".vireo/project.json"), "utf8"));
  add(
    "VIR-PROJECT-001",
    metadata.profile === "frontend" ? "pass" : "fail",
    `Vireo profile: ${metadata.profile ?? "missing"}`,
    "Restore frontend profile metadata.",
  );
} catch {
  add("VIR-PROJECT-001", "fail", "Project metadata is missing or invalid", "Restore .vireo/project.json.");
}
try {
  const managed = JSON.parse(readFileSync(resolve(root, ".vireo/managed-files.json"), "utf8"));
  const valid =
    managed.schemaVersion === 1 &&
    typeof managed.templateCommit === "string" &&
    Array.isArray(managed.files) &&
    managed.files.every(file => typeof file?.path === "string" && /^[a-f0-9]{64}$/u.test(file?.sha256 ?? ""));
  add(
    "VIR-PROJECT-002",
    valid ? "pass" : "fail",
    valid ? "Managed-file provenance is ready" : "Managed-file provenance is invalid",
    "Run the declared Vireo upgrade dry run and restore .vireo/managed-files.json before applying it.",
  );
} catch {
  add(
    "VIR-PROJECT-002",
    "warn",
    "Managed-file provenance is unavailable",
    "Projects created before 0.7 receive provenance during the reviewed 0.6-to-0.7 upgrade.",
  );
}

add(
  "VIR-DEPS-001",
  existsSync(resolve(root, "node_modules")) ? "pass" : "fail",
  "Frontend dependency installation",
  "Run corepack npm run setup.",
);
const packageJson = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8"));
const vireoVersions = Object.entries(packageJson.dependencies ?? {})
  .filter(([name]) => name.startsWith("@vireocodedev/"))
  .map(([, version]) => version);
add(
  "VIR-DEPS-002",
  vireoVersions.length > 0 && new Set(vireoVersions).size <= 2 ? "pass" : "fail",
  "Vireo package compatibility",
  "Use the versions generated by the pinned Template.",
);

const environment = existsSync(resolve(root, ".env.development"))
  ? readFileSync(resolve(root, ".env.development"), "utf8")
  : "";
add(
  "VIR-API-001",
  /VITE_API_MODE=(?:mock|http)/u.test(environment) ? "pass" : "warn",
  "Frontend API mode is explicit",
  "Declare VITE_API_MODE=mock or http.",
);

const pwaProblems = checkPwaSourceContract({ frontendRoot: root });
add(
  "VIR-PWA-001",
  pwaProblems.length === 0 ? "pass" : "fail",
  pwaProblems.length === 0 ? "PWA source contract" : formatPwaContractProblems(pwaProblems),
  "Restore the shared PWA policy, metadata, and icons; run corepack npm run pwa:check:source for details.",
);

const portAvailable = await new Promise(resolveCheck => {
  const socket = createConnection({ host: "127.0.0.1", port: 3000 });
  socket.unref();
  socket.setTimeout(500);
  socket.once("connect", () => {
    socket.destroy();
    resolveCheck(false);
  });
  socket.once("error", () => resolveCheck(true));
  socket.once("timeout", () => {
    socket.destroy();
    resolveCheck(true);
  });
});
add(
  "VIR-PORT-002",
  portAvailable ? "pass" : "fail",
  "Frontend port 3000 availability",
  "Stop the process using port 3000.",
);

for (const result of results)
  console.log(
    `${result.status === "pass" ? "✓" : result.status === "warn" ? "!" : "✗"} ${result.code} ${result.summary}`,
  );
const ok = results.every(result => result.status !== "fail");
const warnings = results.some(result => result.status === "warn");
console.log(
  ok
    ? warnings
      ? "Frontend profile is ready for development with unverified platform warnings."
      : "Frontend profile is ready."
    : "Resolve the failed checks and rerun the doctor.",
);
if (!ok) process.exitCode = 1;
