version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:17"
      timezone: Europe/Zagreb
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
    labels:
      - dependencies
      - security
