-- The consuming application's own schema, in the consumer's own history.
-- Deliberately references nothing the library owns: the point of the split is
-- that these two migration streams are versioned independently.

CREATE TABLE IF NOT EXISTS consumer_widget (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
