export const APP_PAGE_CONTENT_COMPACT_BREAKPOINT = 600;

export const APP_PAGE_CONTENT_WIDE_BREAKPOINT = 1100;

export const APP_PAGE_CONTENT_MIN_WIDTH = 420;

export const APP_PAGE_CONTENT_COMPACT_ENTER_WIDTH = 580;

export const APP_PAGE_CONTENT_COMPACT_EXIT_WIDTH = 620;

export const APP_PAGE_CONTENT_WIDE_ENTER_WIDTH = 1120;

export const APP_PAGE_CONTENT_WIDE_EXIT_WIDTH = 1080;
