-- Saved filter storage owned by vireo-starter-queryengine.
--
-- `entity_name` is a plain VARCHAR rather than an enumerated column: the set of
-- filterable entities belongs to the application, which declares it through its
-- own QueryEntityKey implementation.
--
-- The foreign key into app_user is why this module migrates after auth.

CREATE TABLE IF NOT EXISTS saved_filter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    entity_name VARCHAR(255) NOT NULL,
    engine_version VARCHAR(50) NOT NULL,
    filters_json TEXT NOT NULL,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE,
    modified_at TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR(255),
    modified_by VARCHAR(255),
    keywords VARCHAR(2048),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_saved_filter_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE INDEX IF NOT EXISTS idx_saved_filter_user_id ON saved_filter (user_id);
CREATE INDEX IF NOT EXISTS idx_saved_filter_entity_name ON saved_filter (entity_name);
CREATE INDEX IF NOT EXISTS idx_saved_filter_entity_default ON saved_filter (entity_name, is_default);
