const en = {
  common: {
    ascending: "Ascending",
    ascendingSortDirection: "Ascending sort direction",
    bottomNavigation: "Bottom navigation",
    cancel: "Cancel",
    clearAll: "Clear all",
    clearSearch: "Clear search",
    closeFilters: "Close filters",
    closeNavigation: "Close navigation",
    collapse: "Collapse",
    column: "Sort by",
    create: "Create",
    descending: "Descending",
    descendingSortDirection: "Descending sort direction",
    direction: "Sort direction",
    done: "Done",
    expand: "Expand",
    filters: "Filters",
    loading: "Loading",
    mainNavigation: "Main navigation",
    more: "More",
    noRecordsFound: "No records found.",
    openFilters: "Open filters",
    no: "No",
    yes: "Yes",
    save: "Save",
    search: "Search",
    skipToMainContent: "Skip to main content",
  },
  pwa: {
    newVersionAvailable: "New version available.",
    reload: "Reload",
  },
  network: {
    actionQueued: "Saved offline. Sent when connection returns.",
    actionUnavailable: "This action is unavailable while offline.",
    commandId: "Command ID",
    createdAt: "Created at",
    dataUnavailable: "This data is unavailable while offline.",
    diagnostics: "Offline diagnostics",
    errorMessage: "Error message",
    failedLoadingData: "Failed loading data.",
    httpMethod: "HTTP method",
    lastHeartbeat: "Last heartbeat",
    lastSyncFailure: "Last failure",
    mutationQueuedOffline: "Saved locally — pending sync",
    offline: "Offline",
    offlineBanner: "You are offline. Data may be unavailable and changes are disabled.",
    offlineModeNotSupported: "This action is not available in offline mode yet.",
    offlineQueuePending: "Offline — {{count}} changes pending sync",
    online: "Online",
    owner: "Owner",
    processedAt: "Processed at",
    queuePermanentlyFailed: "{{count}} change(s) failed to sync and need attention",
    queueSize: "Queued commands",
    queueSynced: "Synced",
    reconnecting: "Reconnecting",
    responseStatus: "Response status",
    searchSyncCommands: "Search sync commands",
    status: "Status",
    syncCommands: "Sync commands",
    syncFailures: "Sync failures",
    syncIdle: "Idle",
    syncInProgress: "In progress",
    syncStatus: "Sync status",
    unavailable: "Unavailable",
    url: "URL",
    youAreOffline: "Offline mode",
  },
} as const;

export default en;
