const en = {
  common: {
    actions: "Actions",
    ascending: "Ascending",
    ascendingSortDirection: "Ascending sort direction",
    back: "Back",
    bottomNavigation: "Bottom navigation",
    cancel: "Cancel",
    clearAll: "Clear all",
    clearSearch: "Clear search",
    closeFilters: "Close filters",
    closeNavigation: "Close navigation",
    collapse: "Collapse",
    column: "Sort by",
    create: "Create",
    dark: "Dark",
    delete: "Delete",
    descending: "Descending",
    descendingSortDirection: "Descending sort direction",
    direction: "Sort direction",
    discard: "Discard",
    done: "Done",
    download: "Download",
    edit: "Edit",
    expand: "Expand",
    filters: "Filters",
    language: "Language",
    light: "Light",
    loading: "Loading",
    logout: "Sign out",
    mainNavigation: "Main navigation",
    month: "Month",
    more: "More",
    name: "Name",
    noRecordsFound: "No records found.",
    openFilters: "Open filters",
    profile: "Profile",
    settings: "Settings",
    theme: "Theme",
    year: "Year",
    no: "No",
    yes: "Yes",
    save: "Save",
    search: "Search",
    skipToMainContent: "Skip to main content",
  },
  pwa: {
    newVersionAvailable: "New version available.",
    reload: "Reload",
  },
  network: {
    actionQueued: "Saved offline. Sent when connection returns.",
    actionUnavailable: "This action is unavailable while offline.",
    commandId: "Command ID",
    connectingToLiveUpdates: "Connecting to live updates...",
    createdAt: "Created at",
    dataUnavailable: "This data is unavailable while offline.",
    diagnostics: "Offline diagnostics",
    errorMessage: "Error message",
    failedLoadingData: "Failed loading data.",
    httpMethod: "HTTP method",
    hydratingInBackground: "Syncing local data in background. You can keep using the app.",
    lastHeartbeat: "Last heartbeat",
    lastSyncFailure: "Last failure",
    mutationQueuedOffline: "Saved locally — pending sync",
    offline: "Offline",
    offlineBanner: "You are offline. Data may be unavailable and changes are disabled.",
    offlineModeNotSupported: "This action is not available in offline mode yet.",
    offlineQueuePending: "Offline — {{count}} changes pending sync",
    online: "Online",
    owner: "Owner",
    processedAt: "Processed at",
    queuePermanentlyFailed: "{{count}} change(s) failed to sync and need attention",
    queueSize: "Queued commands",
    queueSynced: "Synced",
    reconnecting: "Reconnecting",
    responseStatus: "Response status",
    searchSyncCommands: "Search sync commands",
    status: "Status",
    syncCommands: "Sync commands",
    syncFailures: "Sync failures",
    syncIdle: "Idle",
    syncInProgress: "In progress",
    syncStatus: "Sync status",
    unavailable: "Unavailable",
    url: "URL",
    youAreOffline: "Offline mode",
  },
  routing: {
    errorChunkMessage:
      "This page could not be loaded. This can happen after an app update — try refreshing the application.",
    errorGenericMessage: "An unexpected error occurred while loading this page.",
    errorOfflineMessage: "You appear to be offline. Check your connection and try again.",
    errorRefresh: "Refresh app",
    errorRetry: "Retry",
    errorTitle: "Something went wrong",
    goHome: "Go to overview",
    notFoundMessage: "The page you requested does not exist or may have moved.",
    notFoundTitle: "Page not found",
    unauthorizedMessage: "You do not have permission to view this page.",
    unauthorizedTitle: "Access denied",
  },
  unsavedChanges: {
    discardAndLeave: "Discard and leave",
    message: "You have unsaved changes. Discard them and leave?",
    savingMessage: "Your changes are being saved. Wait for the save to finish before leaving.",
    savingTitle: "Saving changes",
    stay: "Stay",
    title: "Unsaved changes",
  },
  validation: {
    thisFieldIsRequired: "This field is required.",
  },
  auth: {
    currentUserLoadFailed: "Sign-in succeeded, but your account could not be loaded. Please try again.",
    discardPendingSyncCancel: "Stay signed in",
    discardPendingSyncConfirm: "Sign out and discard",
    discardPendingSyncMessage:
      "{{count}} offline change(s) have not been synced yet. Signing out deletes the local data on this device, so those changes will be lost permanently.",
    discardPendingSyncTitle: "Unsynced offline changes",
    invalidCredentials: "Invalid credentials.",
    password: "Password",
    sessionExpired: "Your session has expired. Sign in again to continue.",
    signIn: "Sign in",
    signInSubtitle: "Enter your credentials to access your account.",
    signedInAs: "Signed in as",
    username: "Username",
  },
  settings: {
    lockNavigationBar: "Lock navigation bar",
    noMaxWidth: "No max width",
    pageBodyMaxWidth: "Page content width",
    pageBodyMaxWidthLg: "Large",
    pageBodyMaxWidthMd: "Medium",
    pageBodyMaxWidthSm: "Small",
    pageBodyMaxWidthXl: "Extra large",
    pageBodyMaxWidthXs: "Extra small",
    title: "Application settings",
    userSettingsSavedSuccessfully: "User settings saved.",
  },
} as const;

export default en;
