const hr = {
  common: {
    ascending: "Uzlazno",
    ascendingSortDirection: "Uzlazni smjer sortiranja",
    bottomNavigation: "Navigacija pri dnu",
    cancel: "Odustani",
    clearAll: "Očisti sve",
    clearSearch: "Očisti pretragu",
    closeFilters: "Zatvori filtere",
    closeNavigation: "Zatvori navigaciju",
    collapse: "Sažmi",
    column: "Sortiraj po",
    create: "Kreiraj",
    descending: "Silazno",
    descendingSortDirection: "Silazni smjer sortiranja",
    direction: "Smjer sortiranja",
    done: "Gotovo",
    expand: "Proširi",
    filters: "Filteri",
    loading: "Učitavanje",
    mainNavigation: "Glavna navigacija",
    more: "Više",
    noRecordsFound: "Nema pronađenih zapisa.",
    openFilters: "Otvori filtere",
    no: "Ne",
    yes: "Da",
    save: "Spremi",
    search: "Search",
    skipToMainContent: "Preskoči na glavni sadržaj",
  },
  pwa: {
    newVersionAvailable: "Dostupna je nova verzija.",
    reload: "Osvježi",
  },
  network: {
    actionQueued: "Spremljeno offline. Šalje se kad se veza vrati.",
    actionUnavailable: "Ova radnja nije dostupna dok ste izvan mreže.",
    commandId: "ID naredbe",
    createdAt: "Kreirano",
    dataUnavailable: "Ovi podaci nisu dostupni dok ste izvan mreže.",
    diagnostics: "Offline dijagnostika",
    errorMessage: "Poruka greške",
    failedLoadingData: "Neuspjelo učitavanje podataka.",
    httpMethod: "HTTP metoda",
    lastHeartbeat: "Zadnji heartbeat",
    lastSyncFailure: "Zadnja greška",
    mutationQueuedOffline: "Spremljeno lokalno — čeka sinkronizaciju",
    offline: "Offline",
    offlineBanner: "Niste povezani s mrežom. Podaci možda nisu dostupni, a promjene su onemogućene.",
    offlineModeNotSupported: "Ova akcija još nije dostupna u offline načinu rada.",
    offlineQueuePending: "Offline — {{count}} promjene čekaju sinkronizaciju",
    online: "Online",
    owner: "Vlasnik",
    processedAt: "Obrađeno",
    queuePermanentlyFailed: "{{count}} promjena nije uspjelo sinkronizirati — potrebna provjera",
    queueSize: "Naredbe u redu",
    queueSynced: "Sinkronizirano",
    reconnecting: "Ponovno povezivanje",
    responseStatus: "Status odgovora",
    searchSyncCommands: "Pretraži naredbe sinkronizacije",
    status: "Status",
    syncCommands: "Naredbe sinkronizacije",
    syncFailures: "Greške sinkronizacije",
    syncIdle: "Miruje",
    syncInProgress: "U tijeku",
    syncStatus: "Status sinkronizacije",
    unavailable: "Nedostupno",
    url: "URL",
    youAreOffline: "Offline način rada",
  },
} as const;

export default hr;
