const hr = {
  common: {
    actions: "Akcije",
    ascending: "Uzlazno",
    ascendingSortDirection: "Uzlazni smjer sortiranja",
    back: "Natrag",
    bottomNavigation: "Navigacija pri dnu",
    cancel: "Odustani",
    clearAll: "Očisti sve",
    clearSearch: "Očisti pretragu",
    closeFilters: "Zatvori filtere",
    closeNavigation: "Zatvori navigaciju",
    collapse: "Sažmi",
    column: "Sortiraj po",
    create: "Kreiraj",
    dark: "Tamna",
    delete: "Obriši",
    descending: "Silazno",
    descendingSortDirection: "Silazni smjer sortiranja",
    direction: "Smjer sortiranja",
    discard: "Odbaci",
    done: "Gotovo",
    download: "Preuzmi",
    edit: "Uredi",
    expand: "Proširi",
    filters: "Filteri",
    language: "Jezik",
    light: "Svijetla",
    loading: "Učitavanje",
    logout: "Odjava",
    mainNavigation: "Glavna navigacija",
    month: "Mjesec",
    more: "Više",
    name: "Naziv",
    noRecordsFound: "Nema pronađenih zapisa.",
    openFilters: "Otvori filtere",
    profile: "Profil",
    settings: "Postavke",
    theme: "Tema",
    year: "Godina",
    no: "Ne",
    yes: "Da",
    save: "Spremi",
    search: "Pretraži",
    skipToMainContent: "Preskoči na glavni sadržaj",
  },
  pwa: {
    newVersionAvailable: "Dostupna je nova verzija.",
    reload: "Osvježi",
  },
  network: {
    actionQueued: "Spremljeno offline. Šalje se kad se veza vrati.",
    actionUnavailable: "Ova radnja nije dostupna dok ste izvan mreže.",
    commandId: "ID naredbe",
    connectingToLiveUpdates: "Povezivanje na promjene uživo...",
    createdAt: "Kreirano",
    dataUnavailable: "Ovi podaci nisu dostupni dok ste izvan mreže.",
    diagnostics: "Offline dijagnostika",
    errorMessage: "Poruka greške",
    failedLoadingData: "Neuspjelo učitavanje podataka.",
    httpMethod: "HTTP metoda",
    hydratingInBackground: "Lokalni podaci se sinkroniziraju u pozadini. Možete nastaviti koristiti aplikaciju.",
    lastHeartbeat: "Zadnji heartbeat",
    lastSyncFailure: "Zadnja greška",
    mutationQueuedOffline: "Spremljeno lokalno — čeka sinkronizaciju",
    offline: "Offline",
    offlineBanner: "Niste povezani s mrežom. Podaci možda nisu dostupni, a promjene su onemogućene.",
    offlineModeNotSupported: "Ova akcija još nije dostupna u offline načinu rada.",
    offlineQueuePending: "Offline — {{count}} promjene čekaju sinkronizaciju",
    online: "Online",
    owner: "Vlasnik",
    processedAt: "Obrađeno",
    queuePermanentlyFailed: "{{count}} promjena nije uspjelo sinkronizirati — potrebna provjera",
    queueSize: "Naredbe u redu",
    queueSynced: "Sinkronizirano",
    reconnecting: "Ponovno povezivanje",
    responseStatus: "Status odgovora",
    searchSyncCommands: "Pretraži naredbe sinkronizacije",
    status: "Status",
    syncCommands: "Naredbe sinkronizacije",
    syncFailures: "Greške sinkronizacije",
    syncIdle: "Miruje",
    syncInProgress: "U tijeku",
    syncStatus: "Status sinkronizacije",
    unavailable: "Nedostupno",
    url: "URL",
    youAreOffline: "Offline način rada",
  },
  routing: {
    errorChunkMessage:
      "Ova stranica nije mogla biti učitana. To se može dogoditi nakon ažuriranja aplikacije — pokušajte osvježiti aplikaciju.",
    errorGenericMessage: "Došlo je do neočekivane greške prilikom učitavanja ove stranice.",
    errorOfflineMessage: "Izgleda da ste offline. Provjerite internetsku vezu i pokušajte ponovno.",
    errorRefresh: "Osvježi aplikaciju",
    errorRetry: "Pokušaj ponovno",
    errorTitle: "Nešto je pošlo po zlu",
    goHome: "Idi na pregled",
    notFoundMessage: "Tražena stranica ne postoji ili je premještena.",
    notFoundTitle: "Stranica nije pronađena",
    unauthorizedMessage: "Nemate dopuštenje za prikaz ove stranice.",
    unauthorizedTitle: "Pristup odbijen",
  },
  unsavedChanges: {
    discardAndLeave: "Odbaci i napusti",
    message: "Imate nespremljene promjene. Odbaciti ih i napustiti stranicu?",
    savingMessage: "Promjene se spremaju. Pričekajte završetak spremanja prije napuštanja stranice.",
    savingTitle: "Spremanje promjena",
    stay: "Ostani",
    title: "Nespremljene promjene",
  },
  validation: {
    thisFieldIsRequired: "Ovo polje je obavezno.",
  },
  auth: {
    currentUserLoadFailed: "Prijava je uspjela, ali vaš račun nije moguće učitati. Pokušajte ponovno.",
    discardPendingSyncCancel: "Ostani prijavljen",
    discardPendingSyncConfirm: "Odjavi se i odbaci",
    discardPendingSyncMessage:
      "Broj nesinkroniziranih offline promjena: {{count}}. Odjavom se lokalni podaci na ovom uređaju brišu pa će te promjene biti trajno izgubljene.",
    discardPendingSyncTitle: "Nesinkronizirane offline promjene",
    invalidCredentials: "Neispravni podaci za prijavu.",
    password: "Lozinka",
    sessionExpired: "Vaša sesija je istekla. Prijavite se ponovno za nastavak.",
    signIn: "Prijava",
    signInSubtitle: "Unesite svoje podatke za pristup računu.",
    signedInAs: "Prijavljen kao",
    username: "Korisničko ime",
  },
  settings: {
    lockNavigationBar: "Zaključaj navigacijsku traku",
    noMaxWidth: "Bez maksimalne širine",
    pageBodyMaxWidth: "Širina sadržaja stranice",
    pageBodyMaxWidthLg: "Široko",
    pageBodyMaxWidthMd: "Srednje",
    pageBodyMaxWidthSm: "Usko",
    pageBodyMaxWidthXl: "Vrlo široko",
    pageBodyMaxWidthXs: "Vrlo usko",
    title: "Postavke aplikacije",
    userSettingsSavedSuccessfully: "Postavke korisnika spremljene.",
  },
} as const;

export default hr;
