import type { CountryCode } from "@/capabilities/country/models/countryCode.models";

/** Deterministic English fallback names for every supported country code. */
export const COUNTRY_ENGLISH_NAMES = {
  AC: "Ascension Island",
  AD: "Andorra",
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AG: "Antigua & Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antarctica",
  AR: "Argentina",
  AS: "American Samoa",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Åland Islands",
  AZ: "Azerbaijan",
  BA: "Bosnia & Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "St. Barthélemy",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivia",
  "BQ-BO": "Bonaire",
  "BQ-SA": "Saba",
  "BQ-SE": "Sint Eustatius",
  BQ: "Caribbean Netherlands",
  BR: "Brazil",
  BS: "Bahamas",
  BT: "Bhutan",
  BV: "Bouvet Island",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CC: "Cocos (Keeling) Islands",
  CD: "Congo - Kinshasa",
  CF: "Central African Republic",
  CG: "Congo - Brazzaville",
  CH: "Switzerland",
  CI: "Côte d’Ivoire",
  CK: "Cook Islands",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cape Verde",
  CW: "Curaçao",
  CX: "Christmas Island",
  CY: "Cyprus",
  CZ: "Czechia",
  DE: "Germany",
  DJ: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  "ES-CT": "Catalonia",
  ES: "Spain",
  ET: "Ethiopia",
  EU: "European Union",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FM: "Micronesia",
  FO: "Faroe Islands",
  FR: "France",
  GA: "Gabon",
  "GB-ENG": "England",
  "GB-NIR": "Northern Ireland",
  "GB-SCT": "Scotland",
  "GB-WLS": "Wales",
  GB: "United Kingdom",
  GD: "Grenada",
  GE: "Georgia",
  GF: "French Guiana",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GS: "South Georgia & South Sandwich Islands",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong SAR China",
  HM: "Heard & McDonald Islands",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  IC: "Canary Islands",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "India",
  IO: "British Indian Ocean Territory",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KM: "Comoros",
  KN: "St. Kitts & Nevis",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Laos",
  LB: "Lebanon",
  LC: "St. Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova",
  ME: "Montenegro",
  MF: "St. Martin",
  MG: "Madagascar",
  MH: "Marshall Islands",
  MK: "North Macedonia",
  ML: "Mali",
  MM: "Myanmar (Burma)",
  MN: "Mongolia",
  MO: "Macao SAR China",
  MP: "Northern Mariana Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NE: "Niger",
  NF: "Norfolk Island",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PM: "St. Pierre & Miquelon",
  PN: "Pitcairn Islands",
  PR: "Puerto Rico",
  PS: "Palestinian Territories",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SG: "Singapore",
  SH: "St. Helena",
  SI: "Slovenia",
  SJ: "Svalbard & Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "South Sudan",
  ST: "São Tomé & Príncipe",
  SV: "El Salvador",
  SX: "Sint Maarten",
  SY: "Syria",
  SZ: "Eswatini",
  TA: "Tristan da Cunha",
  TC: "Turks & Caicos Islands",
  TD: "Chad",
  TF: "French Southern Territories",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "Timor-Leste",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Türkiye",
  TT: "Trinidad & Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "U.S. Outlying Islands",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Vatican City",
  VC: "St. Vincent & Grenadines",
  VE: "Venezuela",
  VG: "British Virgin Islands",
  VI: "U.S. Virgin Islands",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis & Futuna",
  WS: "Samoa",
  XA: "Abkhazia",
  XC: "Northern Cyprus",
  XK: "Kosovo",
  XO: "South Ossetia",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe",
} as const satisfies Record<CountryCode, string>;

export const COUNTRY_NAME_CATALOG_LOCALES = ["en", "hr", "bs", "cnr", "de", "it", "pt", "sl"] as const;

export type CountryNameCatalogLocale = (typeof COUNTRY_NAME_CATALOG_LOCALES)[number];

export const COUNTRY_EXCEPTIONAL_CODES = [
  "EU",
  "IC",
  "AC",
  "TA",
  "XK",
  "XA",
  "XO",
  "XC",
  "BQ-BO",
  "BQ-SA",
  "BQ-SE",
  "GB-ENG",
  "GB-NIR",
  "GB-SCT",
  "GB-WLS",
  "ES-CT",
] as const satisfies readonly CountryCode[];

type CountryExceptionalCode = (typeof COUNTRY_EXCEPTIONAL_CODES)[number];

/** Names Intl.DisplayNames cannot resolve reliably, including upstream subdivision identifiers. */
export const COUNTRY_EXCEPTIONAL_NAMES = {
  en: {
    EU: "European Union",
    IC: "Canary Islands",
    AC: "Ascension Island",
    TA: "Tristan da Cunha",
    XK: "Kosovo",
    XA: "Abkhazia",
    XO: "South Ossetia",
    XC: "Northern Cyprus",
    "BQ-BO": "Bonaire",
    "BQ-SA": "Saba",
    "BQ-SE": "Sint Eustatius",
    "GB-ENG": "England",
    "GB-NIR": "Northern Ireland",
    "GB-SCT": "Scotland",
    "GB-WLS": "Wales",
    "ES-CT": "Catalonia",
  },
  hr: {
    EU: "Europska unija",
    IC: "Kanarski otoci",
    AC: "Otok Uzašašća",
    TA: "Tristan da Cunha",
    XK: "Kosovo",
    XA: "Abhazija",
    XO: "Južna Osetija",
    XC: "Sjeverni Cipar",
    "BQ-BO": "Bonaire",
    "BQ-SA": "Saba",
    "BQ-SE": "Sveti Eustahije",
    "GB-ENG": "Engleska",
    "GB-NIR": "Sjeverna Irska",
    "GB-SCT": "Škotska",
    "GB-WLS": "Wales",
    "ES-CT": "Katalonija",
  },
  bs: {
    EU: "Evropska unija",
    IC: "Kanarska ostrva",
    AC: "Ostrvo Ascension",
    TA: "Tristan da Cunha",
    XK: "Kosovo",
    XA: "Abhazija",
    XO: "Južna Osetija",
    XC: "Sjeverni Kipar",
    "BQ-BO": "Bonaire",
    "BQ-SA": "Saba",
    "BQ-SE": "Sveti Eustahije",
    "GB-ENG": "Engleska",
    "GB-NIR": "Sjeverna Irska",
    "GB-SCT": "Škotska",
    "GB-WLS": "Vels",
    "ES-CT": "Katalonija",
  },
  cnr: {
    EU: "Evropska unija",
    IC: "Kanarska Ostrva",
    AC: "Ostrvo Asension",
    TA: "Tristan da Kunja",
    XK: "Kosovo",
    XA: "Abhazija",
    XO: "Južna Osetija",
    XC: "Sjeverni Kipar",
    "BQ-BO": "Bonaire",
    "BQ-SA": "Saba",
    "BQ-SE": "Sveti Eustahije",
    "GB-ENG": "Engleska",
    "GB-NIR": "Sjeverna Irska",
    "GB-SCT": "Škotska",
    "GB-WLS": "Vels",
    "ES-CT": "Katalonija",
  },
  de: {
    EU: "Europäische Union",
    IC: "Kanarische Inseln",
    AC: "Ascension",
    TA: "Tristan da Cunha",
    XK: "Kosovo",
    XA: "Abchasien",
    XO: "Südossetien",
    XC: "Nordzypern",
    "BQ-BO": "Bonaire",
    "BQ-SA": "Saba",
    "BQ-SE": "Sint Eustatius",
    "GB-ENG": "England",
    "GB-NIR": "Nordirland",
    "GB-SCT": "Schottland",
    "GB-WLS": "Wales",
    "ES-CT": "Katalonien",
  },
  it: {
    EU: "Unione europea",
    IC: "Isole Canarie",
    AC: "Isola Ascensione",
    TA: "Tristan da Cunha",
    XK: "Kosovo",
    XA: "Abcasia",
    XO: "Ossezia del Sud",
    XC: "Cipro del Nord",
    "BQ-BO": "Bonaire",
    "BQ-SA": "Saba",
    "BQ-SE": "Sint Eustatius",
    "GB-ENG": "Inghilterra",
    "GB-NIR": "Irlanda del Nord",
    "GB-SCT": "Scozia",
    "GB-WLS": "Galles",
    "ES-CT": "Catalogna",
  },
  pt: {
    EU: "União Europeia",
    IC: "Ilhas Canárias",
    AC: "Ilha de Ascensão",
    TA: "Tristão da Cunha",
    XK: "Kosovo",
    XA: "Abecásia",
    XO: "Ossétia do Sul",
    XC: "Chipre do Norte",
    "BQ-BO": "Bonaire",
    "BQ-SA": "Saba",
    "BQ-SE": "Santo Eustáquio",
    "GB-ENG": "Inglaterra",
    "GB-NIR": "Irlanda do Norte",
    "GB-SCT": "Escócia",
    "GB-WLS": "País de Gales",
    "ES-CT": "Catalunha",
  },
  sl: {
    EU: "Evropska unija",
    IC: "Kanarski otoki",
    AC: "Otok Ascension",
    TA: "Tristan da Cunha",
    XK: "Kosovo",
    XA: "Abhazija",
    XO: "Južna Osetija",
    XC: "Severni Ciper",
    "BQ-BO": "Bonaire",
    "BQ-SA": "Saba",
    "BQ-SE": "Sveti Evstahij",
    "GB-ENG": "Anglija",
    "GB-NIR": "Severna Irska",
    "GB-SCT": "Škotska",
    "GB-WLS": "Wales",
    "ES-CT": "Katalonija",
  },
} as const satisfies Record<CountryNameCatalogLocale, Record<CountryExceptionalCode, string>>;
