const en = {
  title: "Dev tools",
  subtitle: "Inspect backend query metadata and render filters from it.",
  availableEntities: "Available entities",
  backendConfiguration: "Backend configuration JSON",
  renderedFilterJson: "Rendered filter JSON",
  filters: "Filters",
  noFiltersAdded: "No filters added.",
  addFilter: "+ Add filter",
  relationType: "Relation",
  fromDate: "From",
  toDate: "To",
  rowsJson: "Rows (JSON)",
  rowsJsonPlaceholder: "[]",
  fieldsCountLabel: "fields",
  entityType: "Entity type",
  entityKey: "Entity key",
  operator: "Operator",
  value: "Value",
  noFilterableFields: "No filterable fields were returned for this entity.",
  ok: "OK",
  operators: {
    EQUALS: "Equals",
    NOT_EQUALS: "Not equals",
    CONTAINS: "Contains",
    STARTS_WITH: "Starts with",
    ENDS_WITH: "Ends with",
    IN: "In",
    GREATER_THAN: "Greater than",
    GREATER_OR_EQUAL: "Greater or equal",
    LESS_THAN: "Less than",
    LESS_OR_EQUAL: "Less or equal",
    DATE_RANGE: "Date range",
    IS_NULL: "Is null",
    IS_NOT_NULL: "Is not null",
  },
} as const;

export default en;
