const hr = {
  title: "Dev alati",
  subtitle: "Pregledajte backend metapodatke upita i renderirajte filtere iz njih.",
  availableEntities: "Dostupni entiteti",
  backendConfiguration: "JSON konfiguracije iz backenda",
  renderedFilterJson: "Renderirani JSON filtera",
  filters: "Filteri",
  noFiltersAdded: "Nema dodanih filtera.",
  addFilter: "+ Dodaj filter",
  relationType: "Relacija",
  fromDate: "Od",
  toDate: "Do",
  rowsJson: "Retci (JSON)",
  rowsJsonPlaceholder: "[]",
  fieldsCountLabel: "polja",
  entityType: "Tip entiteta",
  entityKey: "Ključ entiteta",
  operator: "Operator",
  value: "Vrijednost",
  noFilterableFields: "Za ovaj entitet nije vraćeno nijedno filterabilno polje.",
  ok: "OK",
  operators: {
    EQUALS: "Jednako",
    NOT_EQUALS: "Nije jednako",
    CONTAINS: "Sadrži",
    STARTS_WITH: "Počinje s",
    ENDS_WITH: "Završava s",
    IN: "U skupu",
    GREATER_THAN: "Veće od",
    GREATER_OR_EQUAL: "Veće ili jednako",
    LESS_THAN: "Manje od",
    LESS_OR_EQUAL: "Manje ili jednako",
    DATE_RANGE: "Raspon datuma",
    IS_NULL: "Je prazno",
    IS_NOT_NULL: "Nije prazno",
  },
} as const;

export default hr;
